name: flutter_weather
description: A new Flutter project.
version: 1.0.9+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  path_provider: ^2.0.8
  url_launcher: ^6.3.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0

flutter_native_splash:
   color: "#65d3f7"
   image: assets/img/cloudy.png
   android: true
   ios: false
   android_gravity: fill
   android_12:
     color: "#65d3f7"
     image: assets/img/cloudy.png

flutter:
  uses-material-design: true
  assets:
    - assets/